// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6_NuT9rpFD_x6rryFRoekaNRYdmwwfnc',
    appId: '1:943874179662:web:a6d779d4df9182b4df791f',
    messagingSenderId: '943874179662',
    projectId: 'connect-call-cb941',
    authDomain: 'connect-call-cb941.firebaseapp.com',
    storageBucket: 'connect-call-cb941.firebasestorage.app',
    measurementId: 'G-G9P1YW6HT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_4Wc4bOkjSY8GhinqjJxB7h8UnLGDn0k',
    appId: '1:943874179662:android:f162d569275e77b5df791f',
    messagingSenderId: '943874179662',
    projectId: 'connect-call-cb941',
    storageBucket: 'connect-call-cb941.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkQ8sVTX57l0Qzl7MIHaWAK6hwxr5XACU',
    appId: '1:943874179662:ios:c904f54dc6bba80cdf791f',
    messagingSenderId: '943874179662',
    projectId: 'connect-call-cb941',
    storageBucket: 'connect-call-cb941.firebasestorage.app',
    iosBundleId: 'com.example.connectcall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkQ8sVTX57l0Qzl7MIHaWAK6hwxr5XACU',
    appId: '1:943874179662:ios:c904f54dc6bba80cdf791f',
    messagingSenderId: '943874179662',
    projectId: 'connect-call-cb941',
    storageBucket: 'connect-call-cb941.firebasestorage.app',
    iosBundleId: 'com.example.connectcall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6_NuT9rpFD_x6rryFRoekaNRYdmwwfnc',
    appId: '1:943874179662:web:c2f4a9fb46d047b8df791f',
    messagingSenderId: '943874179662',
    projectId: 'connect-call-cb941',
    authDomain: 'connect-call-cb941.firebaseapp.com',
    storageBucket: 'connect-call-cb941.firebasestorage.app',
    measurementId: 'G-XG4S76C7T7',
  );
}
