import 'package:flutter_webrtc/flutter_webrtc.dart';

/// Service responsible for managing WebRTC peer connections in ConnectCall.
class WebRTCService {
  RTCPeerConnection? _peerConnection;
  MediaStream? _localStream;

  /// Getter for the active [RTCPeerConnection] instance.
  RTCPeerConnection? get peerConnection => _peerConnection;

  /// Getter for the active local [MediaStream] instance.
  MediaStream? get localStream => _localStream;

  /// Default ICE configuration using standard public Google STUN servers.
  static const Map<String, dynamic> defaultIceServers = {
    'iceServers': [
      {
        'urls': [
          'stun:stun.l.google.com:19302',
          'stun:stun1.l.google.com:19302',
          'stun:stun2.l.google.com:19302',
        ],
      },
    ],
    'sdpSemantics': 'unified-plan',
  };

  /// Default constraints for the peer connection.
  static const Map<String, dynamic> defaultConstraints = {
    'mandatory': {},
    'optional': [
      {'DtlsSrtpKeyAgreement': true},
    ],
  };

  /// Creates and initializes only the [RTCPeerConnection].
  Future<RTCPeerConnection> createPeerConnectionOnly({
    Map<String, dynamic>? configuration,
    Map<String, dynamic>? constraints,
  }) async {
    final config = configuration ?? defaultIceServers;
    final pcConstraints = constraints ?? defaultConstraints;

    try {
      _peerConnection = await createPeerConnection(config, pcConstraints);
      return _peerConnection!;
    } catch (e) {
      rethrow;
    }
  }

  /// Adds an audio-only local stream to the provided [peerConnection].
  Future<void> addAudioOnlyLocalStream(
    RTCPeerConnection peerConnection, {
    Map<String, dynamic>? constraints,
  }) async {
    final mediaConstraints =
        constraints ?? <String, dynamic>{'audio': true, 'video': false};

    try {
      _peerConnection = peerConnection;
      final stream = await navigator.mediaDevices.getUserMedia(
        mediaConstraints,
      );
      _localStream = stream;

      for (final track in stream.getTracks()) {
        await peerConnection.addTrack(track, stream);
      }
    } catch (e) {
      rethrow;
    }
  }

  /// Adds an audio and video local stream to the provided [peerConnection].
  Future<void> addAudioAndVideoLocalStream(
    RTCPeerConnection peerConnection, {
    Map<String, dynamic>? constraints,
  }) async {
    final mediaConstraints =
        constraints ?? <String, dynamic>{'audio': true, 'video': true};

    try {
      _peerConnection = peerConnection;
      final stream = await navigator.mediaDevices.getUserMedia(
        mediaConstraints,
      );
      _localStream = stream;

      for (final track in stream.getTracks()) {
        await peerConnection.addTrack(track, stream);
      }
    } catch (e) {
      rethrow;
    }
  }

  /// Creates an SDP offer for the provided [peerConnection], sets local description, and returns the offer.
  Future<RTCSessionDescription> createOffer(
    RTCPeerConnection peerConnection, {
    Map<String, dynamic>? constraints,
  }) async {
    try {
      final offer = await peerConnection.createOffer(constraints ?? {});
      await peerConnection.setLocalDescription(offer);
      return offer;
    } catch (e) {
      rethrow;
    }
  }

  /// Sets the remote description on the provided [peerConnection].
  Future<void> setRemoteDescription(
    RTCPeerConnection peerConnection,
    RTCSessionDescription description,
  ) async {
    try {
      _peerConnection = peerConnection;
      await peerConnection.setRemoteDescription(description);
    } catch (e) {
      rethrow;
    }
  }

  /// Creates an SDP answer for the provided [peerConnection], sets local description, and returns the answer.
  Future<RTCSessionDescription> createAnswer(
    RTCPeerConnection peerConnection, {
    Map<String, dynamic>? constraints,
  }) async {
    try {
      final answer = await peerConnection.createAnswer(constraints ?? {});
      await peerConnection.setLocalDescription(answer);
      return answer;
    } catch (e) {
      rethrow;
    }
  }

  /// Listens for ICE candidates generated by the provided [peerConnection].
  void onIceCandidate(
    RTCPeerConnection peerConnection,
    void Function(RTCIceCandidate candidate) onCandidate,
  ) {
    peerConnection.onIceCandidate = onCandidate;
  }

  /// Adds a remote ICE candidate to the provided [peerConnection].
  Future<void> addCandidate(
    RTCPeerConnection peerConnection,
    RTCIceCandidate candidate,
  ) async {
    try {
      await peerConnection.addCandidate(candidate);
    } catch (e) {
      rethrow;
    }
  }

  /// Closes and disposes of the current local stream and peer connection.
  Future<void> dispose() async {
    try {
      if (_localStream != null) {
        for (final track in _localStream!.getTracks()) {
          await track.stop();
        }
        await _localStream!.dispose();
      }
      await _peerConnection?.close();
      await _peerConnection?.dispose();
    } catch (e) {
      rethrow;
    } finally {
      _localStream = null;
      _peerConnection = null;
    }
  }

  // --- Aliases ---

  /// Convenience alias for [addAudioAndVideoLocalStream].
  Future<void> addAudioVideoLocalStream(
    RTCPeerConnection peerConnection, {
    Map<String, dynamic>? constraints,
  }) => addAudioAndVideoLocalStream(peerConnection, constraints: constraints);

  /// Convenience alias for [createOffer].
  Future<RTCSessionDescription> offer(
    RTCPeerConnection peerConnection, {
    Map<String, dynamic>? constraints,
  }) => createOffer(peerConnection, constraints: constraints);

  /// Sets the remote offer (remote description) on the provided [peerConnection].
  Future<void> setOffer(
    RTCPeerConnection peerConnection,
    RTCSessionDescription offer,
  ) => setRemoteDescription(peerConnection, offer);

  /// Convenience alias for [createAnswer].
  Future<RTCSessionDescription> answer(
    RTCPeerConnection peerConnection, {
    Map<String, dynamic>? constraints,
  }) => createAnswer(peerConnection, constraints: constraints);

  /// Sets the remote answer on the provided [peerConnection].
  Future<void> setAnswer(
    RTCPeerConnection peerConnection,
    RTCSessionDescription answer,
  ) => setRemoteDescription(peerConnection, answer);
}
